name: Deno Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Run tests
      run: deno test --allow-read --allow-net tests/unit/*
